# Generated by Django 6.0.3 on 2026-04-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("Motivation", "Motivation"),
                    ("Discipline", "Discipline"),
                    ("Learning", "Learning"),
                ],
                default="Learning",
                max_length=50,
            ),
        ),
    ]
